# Generated by Django 4.0 on 2021-12-28 14:03

from django.db import migrations, models
import uielementdetectorapi.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('uielementdetectorapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(null=True, upload_to=uielementdetectorapi.utilities.user_directory_path),
        ),
    ]
