# Generated by Django 4.0 on 2021-12-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uielementdetectorapi', '0002_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedimage', models.ImageField(upload_to='uploads/')),
                ('codes', models.FileField(null=True, upload_to='codes/')),
                ('jsonfile', models.FileField(null=True, upload_to='jsonfile/')),
                ('detectedimage', models.ImageField(null=True, upload_to='detectedimage/')),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
