# Generated by Django 3.2.10 on 2021-12-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uielementdetectorapi', '0004_detections_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detections',
            name='uploadedimage',
        ),
        migrations.AddField(
            model_name='detections',
            name='confidence',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='detections',
            name='image_to_detect',
            field=models.ImageField(default='', upload_to='uploads/2021_12_30_13_13_59/'),
        ),
    ]
