# Generated by Django 3.2.10 on 2021-12-30 14:37

from django.db import migrations, models
import uielementdetectorapi.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('uielementdetectorapi', '0005_auto_20211230_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detections',
            name='image_to_detect',
            field=models.ImageField(default='', upload_to=uielementdetectorapi.utilities.user_directory_path),
        ),
    ]
