# Generated by Django 3.2.10 on 2022-01-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uielementdetectorapi', '0007_auto_20211230_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detections',
            name='image_to_detect',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
