# Generated by Django 3.2.10 on 2022-01-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uielementdetectorapi', '0010_alter_detections_image_to_detect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detections',
            name='image_to_detect',
            field=models.ImageField(default='', upload_to='', verbose_name='uploads/2022_01_05_00_09_19/'),
        ),
    ]
